---
- name: Install Git, Maven, Docker, HTTPD, Java 17, Terraform, AWS CLI, and Node.js on Amazon Linux 2023
  hosts: all
  become: yes

  vars:
    nvm_version: "0.39.1"  # Specify the version of NVM to install
    node_version: "16"     # Specify the Node.js version to install

  tasks:
    - name: Disable problematic repository (adoptopenjdk)
      command: yum-config-manager --disable adoptopenjdk
      ignore_errors: yes

    - name: Disable problematic repository (corretto)
      command: yum-config-manager --disable corretto
      ignore_errors: yes

    - name: Clear the yum cache
      command: yum clean all

    - name: Update all packages to the latest version
      yum:
        name: "*"
        state: latest

    - name: Install Git
      yum:
        name: git
        state: present

    - name: Install Docker
      yum:
        name: docker
        state: present

    - name: Start and enable Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Add ec2-user to the docker group
      user:
        name: ec2-user
        groups: docker
        append: yes

    - name: Install HTTPD (Apache)
      yum:
        name: httpd
        state: present

    - name: Start and enable HTTPD service
      systemd:
        name: httpd
        state: started
        enabled: yes

    - name: Install Python 3.8 from source
      shell: |
        yum install -y gcc openssl-devel bzip2-devel libffi-devel zlib-devel make
        cd /usr/src
        wget https://www.python.org/ftp/python/3.8.12/Python-3.8.12.tgz
        tar xzf Python-3.8.12.tgz
        cd Python-3.8.12
        ./configure --enable-optimizations
        make altinstall
      args:
        creates: /usr/local/bin/python3.8

    - name: Create a symlink for python3.8
      file:
        src: /usr/local/bin/python3.8
        dest: /usr/bin/python3.8
        state: link

    - name: Download get-pip.py for Python 3.8
      get_url:
        url: https://bootstrap.pypa.io/get-pip.py
        dest: /tmp/get-pip.py

    - name: Install pip3 for Python 3.8
      command: python3.8 /tmp/get-pip.py

    - name: Install Java 17 (Amazon Corretto)
      yum:
        name: java-17-amazon-corretto
        state: present

    - name: Download Maven 3.9.7
      get_url:
        url: https://archive.apache.org/dist/maven/maven-3/3.9.7/binaries/apache-maven-3.9.7-bin.tar.gz
        dest: /tmp/apache-maven-3.9.7-bin.tar.gz

    - name: Extract Maven
      unarchive:
        src: /tmp/apache-maven-3.9.7-bin.tar.gz
        dest: /opt/
        creates: /opt/apache-maven-3.9.7
        remote_src: yes

    - name: Create a symlink for Maven
      file:
        src: /opt/apache-maven-3.9.7
        dest: /opt/maven
        state: link

    - name: Set Maven environment variables
      copy:
        dest: /etc/profile.d/maven.sh
        content: |
          export M2_HOME=/opt/maven
          export PATH=${M2_HOME}/bin:${PATH}

    - name: Apply Maven environment variables
      shell: source /etc/profile.d/maven.sh

    - name: Install Terraform dependencies
      yum:
        name: yum-utils
        state: present

    - name: Add HashiCorp repo
      command: yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo

    - name: Install Terraform
      yum:
        name: terraform
        state: present

    - name: Install AWS CLI using pip3.8
      pip:
        name: awscli
        state: present
        executable: /usr/local/bin/pip3.8

    - name: Restart Docker to apply changes
      systemd:
        name: docker
        state: restarted

    - name: Ensure Docker info command runs without sudo (test Docker installation)
      command: docker info
      become: no
      register: docker_info

    - name: Display Docker info result
      debug:
        var: docker_info.stdout

