---
- name: Install SQL databases on Ubuntu
  hosts: all
  become: yes
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install MySQL
      ansible.builtin.apt:
        name: mysql-server
        state: present

    - name: Ensure MySQL service is running
      ansible.builtin.systemd:
        name: mysql
        state: started
        enabled: yes

    - name: Install PostgreSQL
      ansible.builtin.apt:
        name: postgresql
        state: present

    - name: Ensure PostgreSQL service is running
      ansible.builtin.systemd:
        name: postgresql
        state: started
        enabled: yes

    - name: Install MariaDB
      ansible.builtin.apt:
        name: mariadb-server
        state: present

    - name: Ensure MariaDB service is running
      ansible.builtin.systemd:
        name: mariadb
        state: started
        enabled: yes

    - name: Verify MySQL installation
      ansible.builtin.command: mysql --version
      register: mysql_version
      ignore_errors: yes

    - name: Display MySQL version
      ansible.builtin.debug:
        msg: "MySQL version: {{ mysql_version.stdout }}"

    - name: Verify PostgreSQL installation
      ansible.builtin.command: psql --version
      register: postgres_version
      ignore_errors: yes

    - name: Display PostgreSQL version
      ansible.builtin.debug:
        msg: "PostgreSQL version: {{ postgres_version.stdout }}"

    - name: Verify MariaDB installation
      ansible.builtin.command: mysql --version
      register: mariadb_version
      ignore_errors: yes

    - name: Display MariaDB version
      ansible.builtin.debug:
        msg: "MariaDB version: {{ mariadb_version.stdout }}"

